### ISSUE TITLE
Users: organization needs to have separate data

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/decat_geonode#17]
As per conversation with Christian:
 * users need to belong to an organization
 * organization can have limited data scope:
   * specific hazard types
   * specific regions they are interested in
 * user's role has specific permissions set, see doc:
https://docs.google.com/spreadsheets/d/1-Eqk9ubXhB8YLD2mW4JJuKKWL_QPS5QOM98moL0SmUI/edit#gid=1287517537

 We can start with org data scope. User role will be enforced by frontend at the moment. Backend permissions may take some time to implement.

Things to do:
 * [x] evaluate implementation options
 * [ ] discuss and estimate best option.

**Comment by cezio** [comment]
For groups and data scope:
 * we need one-to-one model for group that will keep limitations,
 * we could override group editing views in geonode, but maybe we can just add another view to edit data scope (it would be easier to do - no need to touch geonode),
 * for api views, i can add few hacks that will add additional filters to querysets based on user's groups data scope.

**Comment by cezio** [comment]
As for per-role permissions, it's a bit more complicated, because integration in geonode is much deeper.  We can add custom permissions, but there needs to be a code that will check those permissions in geonode views. This means we either modify geonode views or wrap them with permissions checking where needed.

In general, django provides three standard permissions for each model (not instance): add, change and delete. For layers, maps and documents there's additional permission, resourcebase.view_resourcebase, which is checked. 

We can enforce custom permissions in decat api views for alarms.

**Comment by ciasio** [comment]
Cezio's questions:
- who should be able to edit group data scope? admin only?

For the purpose of DECAT the admin only would be a sustainable option. For an operational tool, the users in charge for each of 3 roles could need to manage this issue by itself (to adapt faster to specific emergency needs in the real case).

- how we will get organizations into geonode? will they be added manually or with some batch import?

We have to do it for DECAT... So, it is up to us, according to what is more convenient (less time demanding considering both structure setup (db, UI, and in case function) and data entry.

**Comment by ciasio** [comment]
Resuming discussions run by Skype, the general usage of data (layers and maps) access permissions at organization level, have to consider following rights:
- RW (i.e. create and modify) filtered by region, for organizations which are in charge to manage and/or update data of a specific TOPIC;
- RO filtered by region, for organizations which may be interested in the TOPIC related to the data, but not in charge to manage it;
- Deny for organization which are not interested (or have not to deal at all) in data due to its TOPIC or other sort of Keyword to be defined (e.g. "hypothetical scenario" and so on).

Further filtering and permission set has to be considered at role level, for both spatial layers and maps, considering some more options:
Create/Archive (Delete should be avoided)
Edit/Modify
Upload
Download
Promote/Validate.
